version: '2'
services:
      hscout_db:
            image: postgres:9.4.7
            container_name: hscout-db
            ports:
                  - "5432"
            environment:
                  - POSTGRES_USER=odoo
                  - POSTGRES_PASSWORD=odoo
      hscout:
            image: odoo
            container_name: hscout-erp
            volumes:
                  - ./src:/mnt/extra-addons
            ports:
                  - "8069:8069"
            environment:
                  - DB_PORT_5432_TCP_ADDR=hscout_db
                  - DB_PORT_5432_TCP_PORT=5432
                  - DB_ENV_POSTGRES_USER=odoo
                  - DB_ENV_POSTGRES_PASSWORD=odoo
            depends_on:
                  - hscout_db
